version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
  - package-ecosystem: npm
    directory: /server
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: build
  - package-ecosystem: pub
    directory: /app
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: build
